{% set name = "cloudpickle" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cloudpipe/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 49cc8581ce305630b1e179bc083069b21b45db4731e5e3f2ea6fc40b131e1c55

build:
  number: 0
  skip: true # [py<38]
  script:  {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - flit-core

  run:
    - python

test:
  imports:
    - cloudpickle
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/cloudpipe/cloudpickle
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Extended pickling support for Python objects
  description: |
    cloudpickle is extended pickling support for Python objects.
    cloudpickle makes it possible to serialize Python constructs not
    supported by the default pickle module from the Python standard library.
  doc_source_url: https://github.com/cloudpipe/cloudpickle/blob/master/README.md
  dev_url: https://github.com/cloudpipe/cloudpickle

extra:
  recipe-maintainers:
    - jakirkham
    - ogrisel
    - rgbkrk
    - mrocklin
    - nehaljwani
