{% set version = "0.3.0" %}

package:
  name: cloudpickle
  version: {{ version }}

source:
  fn: cloudpickle-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/c/cloudpickle/cloudpickle-{{ version }}.tar.gz
  sha256: b85e68c749052c3fd67697dac677cabc5668f53ac5ce2a7e9e2bc2f42405bcb6

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - cloudpickle

about:
  home: https://github.com/cloudpipe/cloudpickle
  license: BSD 3-Clause
  license_file: LICENSE
  summary: Extended pickling support for Python objects

extra:
  recipe-maintainers:
    - jakirkham
    - ogrisel
    - rgbkrk
    - mrocklin
