{% set version = "3.0.0" %}

package:
  name: cloudpickle
  version: {{ version }}

source:
  fn: cloudpickle-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/c/cloudpickle/cloudpickle-{{ version }}.tar.gz
  sha256: 996d9a482c6fb4f33c1a35335cf8afd065d2a56e973270364840712d9131a882

build:
  number: 0
  skip: true # [py<38]
  script:  {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - flit-core

  run:
    - python


test:
  imports:
    - cloudpickle
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/cloudpipe/cloudpickle
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Extended pickling support for Python objects
  description: |
    cloudpickle is extended pickling support for Python objects.
    cloudpickle makes it possible to serialize Python constructs not
    supported by the default pickle module from the Python standard library.
  doc_source_url: https://github.com/cloudpipe/cloudpickle/blob/master/README.md
  dev_url: https://github.com/cloudpipe/cloudpickle

extra:
  recipe-maintainers:
    - jakirkham
    - ogrisel
    - rgbkrk
    - mrocklin
    - nehaljwani
