{% set name = "cloudpickle" %}
{% set version = "3.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cloudpipe/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7acae4307459d436eee740eea52ec9056f37b8b907d6aef7b0a97a1ccff90ff9

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -v

requirements:
  host:
    - python
    - pip
    - flit-core
  run:
    - python

{% set deselect_test = " --deselect=tests/cloudpickle_file_test.py::CloudPickleFileTests::test_pickling_special_file_handles" %}
{% set deselect_test = deselect_test + " --deselect=tests/cloudpickle_test.py::CloudPickleTest::test_pickling_file_handles" %}
{% set deselect_test = deselect_test + " --deselect=tests/cloudpickle_test.py::Protocol2CloudPickleTest::test_pickling_file_handles" %}

test:
  source_files:
    - tests
  imports:
    - cloudpickle
  requires:
    - pip
    - psutil
    - pytest
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests {{ deselect_test }}

about:
  home: https://github.com/cloudpipe/cloudpickle
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Extended pickling support for Python objects
  description: |
    cloudpickle is extended pickling support for Python objects.
    cloudpickle makes it possible to serialize Python constructs not
    supported by the default pickle module from the Python standard library.
  doc_source_url: https://github.com/cloudpipe/cloudpickle/blob/master/README.md
  dev_url: https://github.com/cloudpipe/cloudpickle

extra:
  recipe-maintainers:
    - jakirkham
    - ogrisel
    - rgbkrk
    - mrocklin
    - nehaljwani
