travis:
  secure:
    BINSTAR_TOKEN: XzAt2ndSiDoyBFWDiTZafLOeKsY49OyEy4477D9lIsCm7WHrkqwyrieMfo2IsPcIRglWpavuoMdfAMYovhIyYRYQ6MZoRQbwlxgan9Yh1sIbT+uP9dM5CG+Oa56cc4qcO4GLOOcpfbBsaM+dCIRAlRzJxOV4hDoUk73Xf29kdvq8iNTHiQytj3/yh+zv5bsC7X2vj7ajgqKFkhsmngrsprB+GSDqalSCNNSa996DMcOpiiJAXpU6JKbnogLq9QacbafGrL424KJx9bm6JVg0IDzZdQf+QKualhNfUrBCDyEVD4ikgAL68GAWxSAQ7ziamCk6sUtZp0J8PdQtgwXvJAeP+2gP6Y0ucL9rBVusNHioEGCGq5EHmLqoWuS064LeE/6f8PZC1PfT9tpZluLbrFmXTA6G+Ay1BYxu7bdzSuQDHuq0BlGPEiqkRNFohCZiCqXproY5PqYPDjTaHFsCzjry4NOI27Yx6uw6NmqlgtDam4wXys7zOvARSq4ZSKFA9wz2dlOFAYaR1XkDClycUb+Qp0RT3mzkfYBZvgjdqj4W+QrkbLiRpqRakcbWJbTbCfgvZzcsN3ueba6D07QY0Y4AbxNweGUB1KFhJeE7lRxlrdi6SJ81eOQ77FtW/rcOuDkwjE2q8SMqoAdSSaVDQrAR1q5wIst3KHMZvi0WXKc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
