travis:
  secure:
    BINSTAR_TOKEN: ihq8zhi/ep1472DqNduz2vipCzofMkQZi1Ax8vd9MjjNIUssTXTpgl5DNrOTOGSawDRe3waIyiIxPF+Rx6t+rKnR2dHnsLCBWt8P4QuxkQ3gHCL2pByW0mTtUV/iejwv6aFCisdmzGMcpbnTNIBYujsM7dZIsnvlzvzTz04qQkfvLFno0Uoo4tLlMEpqA0nAc46IwOsBXwzYTyg9xBKyf3328A1Efgld6Dsppaq/XIrfLehTRoTwwGtNgHNd6vYyiGqkIHP79jg22eGWTDWXbca/8rRInSufvYJxGow8xSLLLQqXBBe+8UWKbrSJHTLr1s1jrDkY/o6pH11GMzRKwtWXup4e6FVkBAMvsWk5V+Yyd7M/mR/vOIbUlqReUOjebX8RZKPdEMAyDMaBvIGo6XN+bV+ptO0mJ52GMGbEa1dYa1HnoDDBUWzVPPF7PM/boyVB5yzkQZrUg+3dYoihbHmqsee4pjXZJ9mZ5UF1kHCYuN9kA06P1FC+mWUu9rOxD+A1dlrsSnm79VeCaJT2p1lfEOqeq80jRC6kiPnaKF4JdDHb1gizTUD3wqEChTdiJu4DEvd0wsgDTHzarsXc6G4LZpph3l55O3MaY44270K7/TUdkus+jTL7KKmhkKP+vMzURf/cwVXddQQOuI5IBGjfWtsRfGe3cogWj1CdF/c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
